meta_product_name: "Ikigai"
meta_title: "Ikigai - Unyielding Elder Trust, Always"
meta_description: "Provides reassurance about the health and medical care of your elderly relatives or dependents"
meta_image: "ikigai2.jpg" # should exist in `app/assets/images/`
twitter_account: "@ikigai_twitter_account"   # required for Twitter Cards
